[build]
  # Next.js のビルドコマンド
  command = "npm run build"
  # ビルド成果物ディレクトリ
  publish = ".next"

# Netlify Next.js プラグイン
[[plugins]]
  package = "@netlify/next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200